## Adapted from :

### 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
# print numpy version and configuration
print(np.__version__)
np.show_config()

1.24.1
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/Nissim/anaconda3/envs/musa-650\\Library\\lib']
    include_dirs = ['C:/Users/Nissim/anaconda3/envs/musa-650\\Library\\include']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/Nissim/anaconda3/envs/musa-650\\Library\\lib']
    include_dirs = ['C:/Users/Nissim/anaconda3/envs/musa-650\\Library\\include']
    language = f77
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['C:/Users/Nissim/anaconda3/envs/musa-650\\Library\\lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/Nissim/anaconda3/envs/musa-650\\Library\\lib']
    langu

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
# create a null vector of size 10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
Y = np.array(range(10, 50))
print(Y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [7]:
# reverse Y
Y = Y[::-1]
print (Y)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
X = np.arange(9).reshape(3,3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
W = np.nonzero([1,2,0,0,4,0])
print(W)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
U = np.eye(3)
print(U)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
V = np.random.random((3,3,3))
print(V)

[[[0.79425622 0.20671536 0.96254291]
  [0.80596938 0.9798819  0.13425795]
  [0.56538632 0.51054689 0.87648388]]

 [[0.96997612 0.62108922 0.65417215]
  [0.95724049 0.42479792 0.16861526]
  [0.62640486 0.09084113 0.09492777]]

 [[0.18074025 0.4803085  0.02525625]
  [0.71913366 0.25904305 0.147534  ]
  [0.09163693 0.5880381  0.90509758]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
V1 = np.random.random((10,10))
Vmin, Vmax = V1.min(), V1.max()
print(Vmin, Vmax)

0.01337416197231256 0.9980317282995931


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
V2 = np.random.random(30)
Vmean = V2.mean()
print(Vmean)

0.5835302206899527


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
V2 = np.ones((10, 10))
V2[1:-1, 1:-1] = 0
print(V2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [38]:
V3 = np.arange(12).reshape(3,4)

# Add a border of 0s to the array
V3 = np.pad(V3, pad_width=1, mode='constant', constant_values=0)

print(V3)

[[ 0  0  0  0  0  0]
 [ 0  0  1  2  3  0]
 [ 0  4  5  6  7  0]
 [ 0  8  9 10 11  0]
 [ 0  0  0  0  0  0]]


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [6]:
V4 = np.arange(25).reshape(5,5)

# change the values of V4 based on the indices of the dictionary
V4[1,0] = 1
V4[2,1] = 2
V4[3,2] = 3
V4[4,3] = 4

print(V4)



[[ 0  1  2  3  4]
 [ 1  6  7  8  9]
 [10  2 12 13 14]
 [15 16  3 18 19]
 [20 21 22  4 24]]


### Bonus: Unrelated (from Guray, in class 2/16): basically, drop the padding on a to return only the middle of the matrix.

In [49]:
a = np.arange(35) + 1
b = a.reshape([5,7])

c = b[1:-1, 1:-1]

# could also do this with a margin of 2, etc.

d = b[2:-2, 2:-2]

print(d)

[[17 18 19]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
e = np.zeros((64))

# replace every other element in each row with 1s
e[::2] = 1

# reshape to 8x8
e = e.reshape(8,8)

print(e)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [22]:
# chatgpt suggests a very similar approach, simplifying the to avoid the reshape
e = np.zeros((8, 8))
e[::2, ::2] = 1

print(e)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
empt = np.zeros((6, 7, 9))

# return the indices of the 100th element
print(np.unravel_index(100, empt.shape))

(1, 4, 1)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [30]:
# generate f, a 5x5 array with random values
f = np.random.random((5,5))

# normalize f
# note that this is min-max normalization, which causes the values to fall between 0 and 1
# other normalization methods are available, such as standardization, which causes the values to fall between -1 and 1
# and also z-score normalization, which causes the values to fall between -3 and 3, with a mean of 0 and a standard deviation of 1
fmax, fmin = f.max(), f.min()

f = (f - fmin)/(fmax - fmin)

print(f)

[[0.41658695 0.6496121  0.99200682 0.63803266 0.50745349]
 [0.68632881 0.80349038 0.2377877  0.         0.21730831]
 [0.56172314 0.03990318 0.98650976 0.18485416 0.18645774]
 [0.04528687 0.65307229 0.6506439  0.49860117 0.25598477]
 [0.16201007 0.36897068 1.         0.95215251 0.36549248]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [31]:
# g is a 5x3 array of random integers
g = np.random.randint(0, 10, (5,3))

h = np.random.randint(0, 10, (3,2))

# multiply g and h
i = np.dot(g, h)

print(g)
print(h)
print(i)

[[5 3 1]
 [4 8 1]
 [8 1 3]
 [8 0 8]
 [0 0 9]]
[[8 9]
 [8 4]
 [1 0]]
[[65 57]
 [97 68]
 [75 76]
 [72 72]
 [ 9  0]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
j = np.random.randint(0, 10, (1, 10))

print(j)

# the following is wrong because the syntax is incorrect:
#j[j > 3 & < 8]  = -j

# according to chatgpt, I can accomplish this with a mask like so:
mask = (j > 3) & (j < 8)
j[mask] = -j[mask]

print(j)

[[8 4 3 9 2 1 7 8 3 7]]
[[ 8 -4  3  9  2  1 -7  8  3 -7]]


#### 26. What is the output of the following script? (★☆☆)

In the latter case, we are calling `sum` from the `numpy` module. As a result, the function is applied along the -1 axis. Since it's a 1D array, the result is simply the sum of the range from 0 to (but not including) 5. The result is 10. 

On the other hand, in the former case, we are calling the built-in `sum` function. As a result, Python adds the sum of `range(5)` to -1, i.e., 10 + (-1) = 9.

(thanks, chatgpt)

In [44]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [43]:
print(range(5))

range(0, 5)


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

According to ChatGPT:

The following expressions are legal for an integer vector Z in Python:

    Z**Z: This expression raises each element of the vector to the power of itself. For example, if Z = [2, 3, 4], then Z**Z would be [4, 27, 256].

    2 << Z >> 2: This expression performs a bit shift operation on each element of the vector. Specifically, it shifts the binary representation of each element 2 bits to the left, and then 2 bits to the right. For example, if Z = [2, 3, 4], then 2 << Z >> 2 would be [2, 4, 8].

    Z <- Z: This expression performs an element-wise comparison between Z and -Z (i.e., the negation of Z). It returns a boolean vector with True values where the corresponding elements in Z are less than the corresponding elements in -Z, and False otherwise.

    1j*Z: This expression multiplies each element of the vector by the imaginary unit j (which represents the square root of -1 in Python). For example, if Z = [2, 3, 4], then 1j*Z would be [2j, 3j, 4j].

    Z/1/1: This expression performs integer division on each element of the vector, effectively returning a copy of Z with the same values. For example, if Z = [2, 3, 4], then Z/1/1 would be [2, 3, 4].

This expression is NOT legal:

    Z<Z>Z: This expression is not legal in Python, and will result in a SyntaxError. The expression is ambiguous and cannot be parsed by the Python interpreter. If you want to compare whether each element in Z is strictly between the corresponding elements in another vector W, you can use the expression W > Z and Z > W.

In [47]:
Z**Z # legal
2 << Z >> 2 # legal
Z <- Z # legal--yo, this is sneaky. it looks just like assignment in R but it isn't
1j*Z # legal
Z/1/1 # legal
Z<Z>Z # illegal

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions?

In [48]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Nissim\AppData\Local\Temp\ipykernel_45744\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Nissim\AppData\Local\Temp\ipykernel_45744\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Nissim\AppData\Local\Temp\ipykernel_45744\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

We can use the `intersect1d` function from NumPy: https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html

In [51]:
k = np.random.randint(1, 50, (5,5))
l = np.random.randint(1, 50, (5,5))

common_vals = np.intersect1d(k, l, return_indices=False)

print(common_vals)

[ 7 18 22 42 44 48]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [55]:
m = np.random.random((5))

m1 = m.astype(int) # converts m to integers
m2 = np.floor(m) # returns the largest integer <= m
m3 = np.ceil(m) # returns the smallest integer >= m
m4 = np.rint(m) # rounds to the nearest integer
m5 = np.trunc(m) # returns the integer part of m
m6 = m // 1 # returns the integer part of m by dividing by 1 and returning result w/o remainder

ms = [m, m1, m2, m3, m4, m5, m6]

for i in ms:
    print(i)

[0.74621893 0.83874759 0.14927038 0.6774937  0.3272106 ]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 0. 1. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

From ChatGPT:

In this code, we first create a 1D array arr with values ranging from 0 to 4 using np.arange(5). We then use np.tile() function to repeat this array 5 times along the rows to get a 5x5 matrix where all rows have the same values.

In [60]:
import numpy as np

# create a 1D array with values ranging from 0 to 4
arr = np.arange(5)

print(arr)

# repeat the array 5 times to get a 5x5 matrix
mat = np.tile(arr, (5, 1))

print(mat)


[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [64]:
# here's chatgpt's solution

vec = np.linspace(0, 1, 12)[1:-1] # the [1:-1] slices to exclude the first (0th) and last values of the array

print(vec)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [53]:
q = np.random.uniform(0,10,10)
q.sort()

print(q)

[1.31421452 1.81802478 2.09910851 3.02889011 3.35794266 4.83351047
 8.61571044 9.28423589 9.64433175 9.71210949]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

Note the following (from ChatGPT):

> np.array_equal(A, B) and A == B are different in the way they compare two arrays. np.array_equal(A, B) checks if the shape and the elements of the two arrays A and B are equal. It returns True if the arrays have the same shape and the elements are equal (within a tolerance). It is a more strict comparison than the == operator and is often preferred when comparing arrays. On the other hand, A == B checks if the corresponding elements of the two arrays A and B are equal. It returns a boolean array of the same shape as A and B where each element is True if the corresponding elements in A and B are equal, and False otherwise. This comparison does not check the shape of the arrays.

So basically, A == B simply compares elementwise what's equal and what's not, while np.array_equal(A, B) checks if the shape and the elements of the two arrays A and B are equal.

In [68]:
A = np.random.random(5)
B = np.random.random(5)

# not this: A == B
# but rather,
np.array_equal(A, B)

False

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [69]:
p = np.random.random(10)

p[p.argmax()] = 0

print(p)

[0.52433296 0.15588688 0.91617242 0.84419664 0.93212799 0.14081788
 0.         0.09158753 0.51452601 0.12453846]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)